---
title: "Wie kann ich ein Solarprojekt starten?"
format: html
date: "2023-06-09"
toc: false
# categories: [Allgemeines]
---

* Denke darüber nach, zu welchen Gebäuden Du eine Beziehung hast
  * wo wohne ich
  * wo arbeite ich
  * wo gehen meine Kinder tagsüber hin
  * wo gehe ich zum Sport
  * etc.
* Schau Dir die Dachfläche an - könnte sie für Photovoltaik-Module geeignet sein?
* Mache Dir mit Online-Recherchemöglichkeiten eine grobe Vorstellung vom Solarpotential des Gebäudes, zum Beispiel hier:
  * [Solarpotenzialkataster der Sächsischen Energieagentur](https://solarkataster-sachsen.de/)
  * [Themenstadtplan der Stadt Dresden](https://stadtplan.dresden.de/?permalink=2HSP4RWx) 
* Sprich den Eigentümer des Gebäudes an und versuche ihn für die Idee eines Solarprojektes zu gewinnen
* Wenn Du ein chancenreiches Gebäude ausgemacht hast, nimm Kontakt zu Menschen auf, die bei der Umsetzung helfen können:
  * zum Beispiel [Energiegenossenschaft Neue Energien Ostsachsen eG (egNEOS)](https://egneos.de/) ist ein hervorragender Ansprechpartner!
* Suche Dir Gleichgesinnte zur Unterstützung, tausche Dich über das Unterfangen aus (zum Beispiel über die Dresden-Solar-[Signal](https://de.wikipedia.org/wiki/Signal_(Messenger))-Gruppe - [Beitrittslink](https://signal.group/#CjQKIPhjhJfJqtR-cg__86GQR-tcPxsLlILNGlyFuyUWFC3vEhAnnXu1V7DAn-mlrrg0Oyef)
) und mache Werbung dafür!
* Du hast weitere Tipps? Leite sie gern an uns weiter :-)