project:
  type: website

website:
  title: "Dresden Solar"
  site-url: "https://dresden-solar.netlify.app/"
  description: "Dokumentation des Photovoltaik-Ausbaus in Dresden"
  favicon: images/dresden-solar.png
  # margin-header: subscribe.html
  # comments: 
  #   hypothesis:
  #     theme: clean
  #     openSidebar: false
  
  navbar:
    # background: orange
    left:
      # - index.qmd
      - news.qmd
      - mitmachen.qmd
      - links.qmd
    right:
      - icon: rss
        href: news.xml
  open-graph: true
  cookie-consent: false
  page-footer: "[Impressum](/impressum.qmd) - [Datenschutzerklärung](/datenschutzerklaerung.qmd)"
  page-navigation: true
format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    strip-comments: true
    title-block-banner: false
lang: de