project:
  type: website
  

website:
  favicon: Sun_Pylon.jpg
  title: "Photovoltaik in Dresden"
  comments: 
    hypothesis:
      theme: clean
      openSidebar: false
  navbar:
    left:
      - news.qmd
      - mitmachen.qmd
      - links.qmd
      - impressum.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



