project:
  type: website
  

website:
  favicon: pv_dd_logo.png
  title: "Photovoltaik in Dresden"
  # comments: 
  #   hypothesis:
  #     theme: clean
  #     openSidebar: false
  comments: 
    utterances:
      repo: sebastian-gerdes/pv-dd-utterances
  navbar:
    left:
      - news.qmd
      - mitmachen.qmd
      - links.qmd
      - impressum.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

lang: de