project:
  type: website
  
website:
  title: "Dresden Solar"
  site-url: https://pv-dd.netlify.app/
  description: "Dokumentation des Photovoltaik-Ausbaus in Dresden"
  favicon: pv_dd_logo.png
  # margin-header: subscribe.html
  # comments: 
  #   hypothesis:
  #     theme: clean
  #     openSidebar: false
  navbar:
    # background: orange
    left:
      - index.qmd
      - news.qmd
      - mitmachen.qmd
      # - next_steps.qmd
      - links.qmd
      - impressum.qmd
    right:
      - icon: rss
        href: news.xml
  open-graph: true
  cookie-consent: false
  page-footer: "Aktuell ist diese Webseite im Entwurfsstadium und noch nicht im 'Aktivmodus' - [ToDos](https://etherpad.wikimedia.org/p/dresdensolar)" 
format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    strip-comments: true

lang: de