project:
  type: website
  

website:
  favicon: pv_dd_logo.png
  title: "Dresden Solar"
  # comments: 
  #   hypothesis:
  #     theme: clean
  #     openSidebar: false
  navbar:
    # background: orange
    left:
      - index.qmd
      - news.qmd
      - mitmachen.qmd
      - links.qmd
      - impressum.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

lang: de