project:
  type: website
  

website:
  favicon: pv_dd_logo.png
  title: "Dresden Solar"
  # comments: 
  #   hypothesis:
  #     theme: clean
  #     openSidebar: false
  navbar:
    # background: orange
    left:
      - index.qmd
      - news.qmd
      - mitmachen.qmd
      - next_steps.qmd
      - links.qmd
      - impressum.qmd
  open-graph: true
  cookie-consent: false
  page-footer: "Aktuell ist diese Webseite im Entwurfsstadium und noch nicht im 'Aktivmodus'" 
format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    strip-comments: true

lang: de