---
title: "Links"
---

## Seiten der Stadt Dresden
* [Allgemeines zum Thema Klima](https://www.dresden.de/de/stadtraum/umwelt/umwelt/klima-und-energie.php?pk_campaign=Shortcut&pk_kwd=klima)
* [Klimaschutzseite der Stadt Dresden](https://www.dresden.de/de/stadtraum/umwelt/umwelt/klima-und-energie/Klimaschutz.php)
* [Integriertes Energie- und Klimaschutzkonzept der Stadt Dresden](https://www.dresden.de/de/stadtraum/umwelt/umwelt/klima-und-energie/klimaschutz/klimaschutzkonzept.php) - ein neues ist in Arbeit - hier wäre wichtig, sinnvolle Ziele zu setzen!

## Solarpotenzialkataster Sächsische Energieagentur
* Enthält Schätzungen zu möglicher Leistung und Wirtschaftlichkeit von Photovoltaikanlagen für quasi alle Gebäude in Sachsen
* [Link zum Kataster](https://solarkataster-sachsen.de/)

## Solarpotentiale nach Berechnung Leibniz-Institut für ökologische Raumentwicklung Dresden
* Enthält Schätzungen zu möglicher Leistung und Wirtschaftlichkeit von Photovoltaikanlagen für quasi aller Gebäude in Dresden
* [Bericht der Stadt Dresden](https://www.dresden.de/de/rathaus/aktuelles/pressemitteilungen/2023/03/pm_031.php?mtm_kwd=Stadtentwicklung+und+Umwelt&mtm_campaign=newsletter)
* [Link zu Berechnungsmöglichkeit im Themenstadtplan](https://stadtplan.dresden.de/?permalink=2HSP4RWx) - recht freundliche Benutzeroberfläche
* [Link zum 3D-Modell](https://arcg.is/1Obb1X0) - etwas langsam in der Bedienung

<!-- ## Geothermische Karte des Landes Sachsen der möglichen Entzugsleistung für Wärmepumpen) -->
<!-- * [Link zur Webseite](https://www.umwelt.sachsen.de/umwelt/infosysteme/ida/p/gtk50?) -->

## Wattbewerb
* Verein, der eine Art "Photovoltaik"-Ralley gestartet hat
* [Link zur Webseite](https://wattbewerb.de/)

## Energiegenossenschaft Neue Energien Ostsachsen eG (egNEOS)
* Energiegenossenschaft, die Bürgerbeteiligung beim Ausbau erneuerbarer Energien fördern möchte und auch hinter dieser (www.dresden-solar.de) Webseite steht
* [Link zur Webseite](https://egneos.de/)

## Solarcamp for Future
* Unter anderem Workshops, in denen eine Qualifizierung zur Photovoltaik-Hilfsfachkraft erfolgt -  [Solarcamp for Future](https://solarcamp-for-future.de/)

<!-- ## Ökostromrechner -->
<!-- * [Link](https://wirklich-gruen.de/) -->

<!-- ## Carus Green -->
<!-- * Nachhaltigkeitsinitiative des Universitätsklinikums Dresden -->
<!-- * Bisher keine gute Webpräsenz gefunden -->

<!-- ## Fridays For Future Dresden -->
<!-- * Initiative, die Klimaschutz voranbringen möchte -->
<!-- * [Link](https://fffdd.de/) -->
<!-- * [Link zu sehr interessantem Blogpost](https://fffdd.de/blog/treibhausgasbilanz/) von Fridays For Future Dresden -->

<!-- ## Health for Future Dresden -->
<!-- * [Kontaktdaten zur Ortsgruppe Dresden](https://healthforfuture.de/health-for-future-ortsgruppen/) -->

<!-- ## Parents for Future Dresden -->
<!-- * [Link](https://www.parentsforfuture.de/de/dresden) -->

## Dresden Zero
* Initiative Dresden bis zum Jahr 2035 klimaneutral zu machen
* [Link zur Webseite](https://dresdenzero.de/)

## Vereinigung zur Förderung der Nutzung Erneuerbarer Energien Sachsen
* [Link zur Webseite](https://www.vee-sachsen.de/node/)

## Solaroffensive Dresden
* [Link](https://www.saechsische.de/dresden/politik/welche-dresdner-daecher-sind-fuer-solaranlagen-geeignet-5831744.html)
* [Link](https://www.dresden.de/de/rathaus/aktuelles/pressemitteilungen/2022/12/pm_069.php)

<!-- ## Sachsenenergie -->
<!-- * [Link](https://www.sachsenenergie.de/) -->
<!-- * Für mich auf den ersten Blick keine aussagekräftigen Informationen zum Thema Energiewende etc. ersichtlich -->

<!-- ## Regionaler Solarverein Dresden e. V. RSD  -->
<!-- * [Link](https://branchenbuch.meinestadt.de/dresden/company/11997431/) -->

<!-- ## Infos zum Thema Energie des Landes Sachsen -->
<!-- [Link](https://www.energie.sachsen.de/index.html) -->

<!-- ## Netzwerk Eurosolar -->
<!-- * Überregionaler Verein zur Förderung erneuerbarer Energien: [Link](https://www.eurosolar.de) -->
