---
title: "Next Steps"
---

::: {.callout-note}
## 
Diese Seite sollte dann irgendwann in den internen Bereich verschwinden.
:::


## Geplante nächste Schritte:
* Feedback einholen
* Institutionen, die schon Photovoltaikanlagen installiert haben anschreiben mit der Frage, ob sie hier die Geschichte ihrer Photovoltaikanlage berichten wollen
* Auf anderen Seiten um Verlinkung / Berichterstattung über das Projekt bitten
* Newsletter-Funktion ergänzen ([Howto](https://quarto.org/docs/websites/website-blog.html#subscriptions)), z. B. über:
  + [Mailjet](https://www.mailjet.com/pricing/) - wird auch von Health for Future genutzt
  + [Mailchimp](https://mailchimp.com/de/?currency=EUR)
  + Aktueller Stand: 
    - Mailjet-Lösung ausprobiert, funktioniert, erscheint mir jedoch 'overpowered', deswegen wieder rausgenommen
    - Googlegroups zwingt einen immer wieder zur Verwendung einer gmail-Adresse - nicht so schön
    - aktuell manuelle Mailingliste über Postfach dresden-solar bei posteo.de favorisiert
    - schön wäre so etwas wie eine [mailman](http://www.list.org/)-Mailingliste denke (schlicht, nichtkommerziell, kein Tracking, komfortabel)
* Rechtliche Aspekte klären
  + Insbesondere: Inweiweit dürfen Menschen, die versuchen eine Institution zur Installation einer Photovoltaikanlage zu motivieren davon berichten? Macht es einen Unterschied, ob man bei der Organisation arbeitet? 
  + Welche rechtlichen Risiken sind mit diesem Projekt (Presserecht etc.) verbunden? Wie kann gegen diese Risiken abgesichert werden?
  + Impressum: Hinweise zur Verarbeitung von Daten etc. so passend?
* Besseren Webseitennamen / Domäne organisieren (derzeit: https://pv-dd.netlify.app/)
  + www.dresdensolar.net oder www.dresden-solar.de?
* Besseres Bild für Startseite
