---
title: 'Konzept und ToDos'
embed-resources: true
toc: true
---

## Change image dimensions
```{r}
library('magick')
library('fs')

change_image_dimensions <- Vectorize(
  function(file_name_in, new_pixel_width = 200) {
    file_name_out <- paste0(path_ext_remove(file_name_in), '_small.png')
    my_image <- image_read(file_name_in)
    my_image_small <- 
      image_resize(my_image, 
                   geometry = geometry_size_pixels(width = new_pixel_width))
    image_write(my_image_small, path = file_name_out)
    return(my_image_small)
  })

files <- c('../posts/2023-06-09-solarfest-dresden/ensemble_incroyable.png')

files <- c('images/links_logos/logo_for_future.png')

change_image_dimensions(files, new_pixel_width = 800)

```


## ToDos aktuell
* Institutionen, die schon Photovoltaikanlagen installiert haben anschreiben mit der Frage, ob sie hier die Geschichte ihrer Photovoltaikanlage berichten wollen
* Auf anderen Seiten um Verlinkung / Berichterstattung über das Projekt bitten
* Impressum: Hinweise zur Verarbeitung von Daten etc. so passend?
* Besseres Bild für Startseite
* Soll es eine explizite "Über das Projekt"-Seite geben? Evtl. eher eine FAQ-Seite einfügen? --> eher so etwas wie einen Post zum Start des Projektes
* Welche rechtlichen Risiken sind mit diesem Projekt (Presserecht etc.) verbunden? Wie kann gegen diese Risiken abgesichert werden?


## ToDos für irgendwann
* Kommentare über [Disqus](https://help.disqus.com/en/articles/1717112-universal-embed-code) statt über utterances, da Disqus weiter verbreitet? Nachteil: mehr Tracking, weniger Schutz der Privatsphäre
* Newsletter-Funktion asubauen ([Howto](https://quarto.org/docs/websites/website-blog.html#subscriptions)), z. B. über:
  * [Mailjet](https://www.mailjet.com/pricing/) - wird auch von Health for Future genutzt
  * [Mailchimp](https://mailchimp.com/de/?currency=EUR)
  * Aktueller Stand: 
    * Mailjet-Lösung ausprobiert, funktioniert, erscheint mir jedoch 'overpowered', deswegen wieder rausgenommen
    * Googlegroups zwingt einen immer wieder zur Verwendung einer gmail-Adresse - nicht so schön
    * aktuell manuelle Mailingliste über Postfach dresden-solar bei posteo.de favorisiert
    * schön wäre so etwas wie eine [mailman](http://www.list.org/)-Mailingliste denke (schlicht, nichtkommerziell, kein Tracking, komfortabel)~~


## Vorläufig erledigt
* Inwieweit dürfen Menschen, die versuchen eine Institution zur Installation einer Photovoltaikanlage zu motivieren davon berichten? Macht es einen Unterschied, ob man bei der Organisation arbeitet?  
  --> nur mit explizitem Einverständnis der Personen / Institution arbeiten
* Wer tritt als Autor eines Posts auf? Wer ist Redakteur? Was bedeutet das jeweils?  
--> Autor: derjenige der es geschrieben hat, Redakteur Sebastian Gerdes, Impressum: egNEOS 
* Besseren Webseitennamen / Domäne organisieren (derzeit: https://pv-dd.netlify.app/)  
--> sollte auf www.dresden-solar.de hinauslaufen

## Notizen
* [Historische Seite](http://web.archive.org/web/20170222141836/http://www.buergerkraftwerk.de/index.php?id=76)

