---
title: "Wieviel Energie liefert die Sonne?"
format: html
date: "2023-03-19"
toc: true
# categories: [Allgemeines]
---

```{r}
#| label: Berechnungen
#| include: false
d3 <- function(x) {
  format(x, scientific = TRUE, digits = 3)
}
seconds_per_year <- 365.25 * 24 * 60 * 60

surface_earth_m2 <- 5.1e14
surface_germany_m2 <- 3e5 * 1e6

energy_sun_per_year_joule <- surface_earth_m2 * seconds_per_year * 1340
energy_sun_per_year_kWh <- energy_sun_per_year_joule / 3.6e6

consumption_world_per_year_joule <- 5.74e20
consumption_world_per_year_kWh <- consumption_world_per_year_joule / 3.6e6

consumption_germany_per_year_joule <- (3.3 * 1e3 * 1e9 * 3.6e6)
consumption_germany_per_year_kWh <- consumption_germany_per_year_joule / 3.6e6


```

Um einordnen zu können, wie viel Energie die Sonne tagtäglich auf die Erde schickt, habe ich ein paar Zahlen zusammengetragen und versucht diese in sinnvoller Weise miteinander zu verknüpfen.


## Wie viel Energie liefert die Sonne?
Zuerst einmal wollte ich wissen wieviel Energie ($E$) im physikalischen Sinne (Joules oder kWh) die Sonne pro Tag / Jahr auf die Erde schickt.

Dazu habe ich [hier](https://www.dlr.de/blogs/home/energie/frage-der-woche-wie-viel-energie-schickt-uns-die-sonne-jeden-tag.aspx) die Angabe gefunden, dass die Sonne auf das Jahr und die Erdoberfläche gemittelt mit einer Leistung von 1340 Watt pro Quadratmeter auf die Erde strahlt. In den weiteren Überlegungen wenden wir die grobe Näherung an, dass dieser Mittelwert 1340 Watt pro Quadratmeter pro Jahr für alle Fleckchen auf der Erde gilt.

Die Oberfläche der Erde beträgt laut [Wikipedia](https://de.wikipedia.org/wiki/Erdoberfl%C3%A4che) ca. 510 Millionen Quadratkilometer.

Daraus ergibt sich eine Gesamtenergie pro Jahr von `r d3(energy_sun_per_year_joule)` Joules. 

## Wieviel Energie verbrauchen die Menschen?
Laut [Wikipedia](https://de.wikipedia.org/wiki/Weltenergiebedarf) beträgt der menschliche Weltenergiebedarf 574 Exajoule = 5.74e20 J. 


Die Welt liefert also ca. `r d3(energy_sun_per_year_joule / consumption_world_per_year_joule)` mal, also knapp 40000 mal, so viel Energie wie von den Menschen verbraucht wird.

Bei einem Photovoltaik-Wirkungsgrad von 10% müssten grob genähert mithin xx% der Erde mit PV-Anlagen bedeckt sein, um den Gesamtenergiebedarf der Menschheit zu befriedigen. 
Das entspricht der (für mich überraschend kleinen) Fläche von ca xx m^2 pro Mensch.

## Wie ist die Situation in Deutschland
Der Energiebedarf Deutschlands betrug laut [Wikipedia](https://de.wikipedia.org/wiki/Weltenergiebedarf) im Jahr 2020 ca. `r d3(consumption_germany_per_year_joule)` Joules. 

Damit müssten in Deutschland pro Person x qm mit Photovoltaikanlagen bedeckt sein, um den Primärenergiebedarf zu decken.

## Fazit
Es handelt sich hierbei um eine wirklich sehr grobe Berechnung. In den folgenden Punkten Näherungen:

* Sonnenstrahlung überall gleich
* Wirkungsgrad
* Speicherung von Energie vernachlässigt
